version: '3.9'
services:
  eureka-server-container:
    build: eurekaServer
    container_name: eureka-server-container
    restart: always
    ports:
      - "8761:8761"
    expose:
      - '8761'
    links:
      - config-server-container
  config-server-container:
    build: configServer
    container_name: config-server-container
    restart: always
    ports:
      - "8888:8888"
    expose:
      - '8888'
  gateway-container:
    build: gateway
    restart: always
    container_name: gateway-container
    ports:
      - "8080:8080"
    expose:
      - '8080'
    links:
      - config-server-container
      - eureka-server-container
  api-music:
    build: api-music
    container_name: api-music
    restart: always
    ports:
      - "9001:9001"
    expose:
      - '9001'
    links:
      - config-server-container
      - eureka-server-container
      - mysql-container
      - rabbitmq-container
      - zipkin-server-container
  api-playlist:
    build: api-playlist
    container_name: api-playlist
    restart: always
    ports:
      - "9002:9002"
    expose:
      - '9002'
    links:
      - config-server-container
      - eureka-server-container
      - mysql-container
      - rabbitmq-container
      - zipkin-server-container
  api-sugeridos:
    build: api-sugeridos
    container_name: api-sugeridos
    restart: always
    ports:
      - "9003:9003"
    expose:
      - '9003'
    links:
      - config-server-container
      - eureka-server-container
      - mongo-container
      - rabbitmq-container
      - zipkin-server-container
  mysql-container:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'primemusic-dev-mysql'
      MYSQL_USER: 'usr-primemusic-mysql'
      MYSQL_PASSWORD: 'pwd-primemusic-mysql'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'primemusic-dev-mongo'
      MONGO_INITDB_ROOT_USERNAME: 'usr-primemusic-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-primemusic-mongo'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin-server-container:
    image: openzipkin/zipkin-slim
    container_name: zipkin-server-container
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    expose:
      - 9411
    depends_on:
      - storage-container
  storage-container:
    image: busybox:1.31.0
    container_name: storage-container
  rabbitmq-container:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672