server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-suggestion
  data:
    mongodb:
      username: usr-primemusic-mongo
      password: pwd-primemusic-mongo
      database: primemusic-dev-mongo
      port: 27017
      host: localhost

resilience4j.retry:
  instances:
    retryMusic:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException



resilience4j.circuitbreaker:
  instances:
    clientMusic:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka