server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictorica/java-spring-cloud-poc
          default-label: develop
          force-pull: true
          search-paths: configData
