server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-playlist
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/primemusic-dev-mysql
    username: usr-primemusic-mysql
    password: pwd-primemusic-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://eureka-server-container:8761/eureka